AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/SelectByRegexp:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false
