name: CI macos
on:
  push:
  pull_request:

jobs:
  rspec:
    name: Unit tests
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - { ruby_version: 3.3, sentry_version: "~> 6.0" }
          - { ruby_version: 3.4, sentry_version: "~> 6.0" }
          - { ruby_version: 3.4, sentry_version: "~> 7.0" }
          - { ruby_version: 4.0, sentry_version: "~> 6.0" }
          - { ruby_version: 4.0, sentry_version: "~> 7.0" }
          - { ruby_version: jruby, sentry_version: "~> 6.0" }
    env:
      SENTRY_VERSION: ${{ matrix.sentry_version }}
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: ${{ matrix.ruby_version }}

      - name: Run specs
        run: |
          bundle install --jobs 4 --retry 3 --no-cache
          bundle exec rspec

      - uses: coverallsapp/github-action@v2
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
        with:
          flag-name: ruby-${{ join(matrix.*, '-') }}
          parallel: true
