name: CI2
on:
  push:
    branches: master
  pull_request:

jobs:
  rspec:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { ruby_version: 3.1 }
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: ${{ matrix.ruby_version }}

      - name: Run specs
        run: |
          bundle install --jobs 4 --retry 3 --no-cache
          bundle exec rspec

      - run: |
          curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz
          curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-checksums.txt
          cat coveralls-checksums.txt | grep coveralls-linux.tar.gz | sha256sum --check
          tar -xzf coveralls-linux.tar.gz
          ./coveralls --parallel --job-flag ruby-${{ join(matrix.*, '-') }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
      # - uses: coverallsapp/github-action@v2
      #   env:
      #     COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
      #   with:
      #     flag-name: ruby-${{ join(matrix.*, '-') }}
      #     parallel: true
