name: CI3
on:
  push:
    branches: master
  pull_request:

jobs:
  rspec:
    name: Unit tests
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - { ruby_version: jruby }
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: ${{ matrix.ruby_version }}

      - name: Run specs
        run: |
          bundle install --jobs 4 --retry 3 --no-cache
          bundle exec rspec

      # - uses: coverallsapp/github-action@v2
      - uses: mrexox/coveralls-github-action@feat/add-compare_ref-and-compare_sha-options
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
        with:
          flag-name: ruby-${{ join(matrix.*, '-') }}
          parallel: true
          compare-ref: test/coverage-base
